name: seventh_sense_ai_coach
description: "Seventh Sense AI Coach - Habit tracking with AI motivation"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State & Models
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Navigation & UI
  go_router: ^14.0.0
  flutter_animate: ^4.2.0
  lottie: ^3.0.0
  flutter_staggered_animations: ^1.1.1

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

  # Platform
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  share_plus: ^9.0.0
  file_picker: ^8.0.0
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/
